using System.Text;
using KaylesStepsRecorder.Core.Enums;
using KaylesStepsRecorder.Core.Interfaces;
using KaylesStepsRecorder.Core.Models;

namespace KaylesStepsRecorder.Export;

/// <summary>
/// Renders a session as a Markdown document suitable for attaching to Jira,
/// GitHub issues, or pasting into documentation.
/// </summary>
public sealed class MarkdownExportService : IExportService
{
    public bool SupportsFormat(ExportFormat format) => format == ExportFormat.Markdown;

    public async Task<string> ExportAsync(RecordingSession session, ExportOptions options)
    {
        if (session is null) throw new ArgumentNullException(nameof(session));
        if (options is null) throw new ArgumentNullException(nameof(options));
        if (string.IsNullOrWhiteSpace(options.OutputPath))
            throw new ArgumentException("OutputPath is required", nameof(options));

        var m = session.Metadata;
        var sb = new StringBuilder();

        string title = string.IsNullOrWhiteSpace(m.BugTitle) ? "Recorded Session" : m.BugTitle;
        sb.AppendLine($"# {title}").AppendLine();

        if (options.IncludeMetadata)
        {
            sb.AppendLine("## Metadata").AppendLine();
            AppendMetaRow(sb, "Application", m.ApplicationUnderTest);
            AppendMetaRow(sb, "Build / Version", m.BuildVersion);
            AppendMetaRow(sb, "Tester", m.TesterName);
            AppendMetaRow(sb, "Environment", m.TestEnvironment);
            AppendMetaRow(sb, "Priority", m.Priority);
            AppendMetaRow(sb, "Severity", m.Severity);
            AppendMetaRow(sb, "Recorded", session.CreatedAt.ToLocalTime().ToString("yyyy-MM-dd HH:mm"));
            sb.AppendLine();
        }

        if (!string.IsNullOrWhiteSpace(m.ExpectedResult))
        {
            sb.AppendLine("## Expected Result").AppendLine().AppendLine(m.ExpectedResult).AppendLine();
        }
        if (!string.IsNullOrWhiteSpace(m.ActualResult))
        {
            sb.AppendLine("## Actual Result").AppendLine().AppendLine(m.ActualResult).AppendLine();
        }
        if (!string.IsNullOrWhiteSpace(m.AdditionalNotes))
        {
            sb.AppendLine("## Additional Notes").AppendLine().AppendLine(m.AdditionalNotes).AppendLine();
        }

        sb.AppendLine("## Reproduction Steps").AppendLine();

        string outputDir = Path.GetDirectoryName(options.OutputPath) ?? string.Empty;
        var steps = session.Steps
            .Where(s => !s.IsDeleted || options.IncludeDeletedSteps)
            .OrderBy(s => s.StepNumber);

        foreach (var step in steps)
        {
            sb.Append(step.StepNumber).Append(". **").Append(EscapeMd(step.Description)).Append("**");

            if ((step.Flags & StepFlag.Important) != 0) sb.Append(" _[IMPORTANT]_");
            if ((step.Flags & StepFlag.Bug) != 0) sb.Append(" _[BUG]_");

            if (options.IncludeTimestamps)
            {
                sb.Append("  \n   _").Append(step.Timestamp.ToLocalTime().ToString("HH:mm:ss")).Append("_");
            }

            if (!string.IsNullOrWhiteSpace(step.UserNote))
            {
                sb.Append("  \n   > ").Append(EscapeMd(step.UserNote));
            }

            if (options.IncludeScreenshots && !step.IsRedacted && !string.IsNullOrEmpty(step.ScreenshotPath)
                && File.Exists(step.ScreenshotPath))
            {
                try
                {
                    string rel = Path.GetRelativePath(outputDir, step.ScreenshotPath).Replace('\\', '/');
                    sb.AppendLine().Append("   ![Step ").Append(step.StepNumber).Append("](").Append(rel).Append(')');
                }
                catch
                {
                    // ignore path errors
                }
            }

            sb.AppendLine().AppendLine();
        }

        sb.AppendLine("---").AppendLine($"_Generated by Kayle's Steps Recorder on {DateTime.Now:yyyy-MM-dd HH:mm}_");

        Directory.CreateDirectory(outputDir);
        await File.WriteAllTextAsync(options.OutputPath, sb.ToString(), Encoding.UTF8).ConfigureAwait(false);
        return options.OutputPath;
    }

    private static void AppendMetaRow(StringBuilder sb, string label, string? value)
    {
        if (string.IsNullOrWhiteSpace(value)) return;
        sb.Append("- **").Append(label).Append("**: ").AppendLine(value);
    }

    private static string EscapeMd(string? text)
    {
        if (string.IsNullOrEmpty(text)) return string.Empty;
        return text.Replace("\\", "\\\\").Replace("*", "\\*").Replace("_", "\\_")
                   .Replace("[", "\\[").Replace("]", "\\]").Replace("`", "\\`");
    }
}
